<?php
$data = array (
  146 => 
  array (
    'cat_id' => '146',
    'cat_name' => '日用百货/超市',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 0,
    'id' => '146',
    'name' => '日用百货/超市',
  ),
  148 => 
  array (
    'cat_id' => '148',
    'cat_name' => '个人洗护',
    'measure_unit' => '',
    'parent_id' => '146',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '6',
    'goods_num' => 0,
    'level' => 1,
    'id' => '148',
    'name' => '个人洗护',
  ),
  191 => 
  array (
    'cat_id' => '191',
    'cat_name' => '香皂',
    'measure_unit' => '',
    'parent_id' => '148',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '191',
    'name' => '香皂',
  ),
  183 => 
  array (
    'cat_id' => '183',
    'cat_name' => '洗发水',
    'measure_unit' => '',
    'parent_id' => '148',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => 3,
    'level' => 2,
    'id' => '183',
    'name' => '洗发水',
  ),
  181 => 
  array (
    'cat_id' => '181',
    'cat_name' => '沐浴露',
    'measure_unit' => '',
    'parent_id' => '148',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '181',
    'name' => '沐浴露',
  ),
  182 => 
  array (
    'cat_id' => '182',
    'cat_name' => '牙刷',
    'measure_unit' => '',
    'parent_id' => '148',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '182',
    'name' => '牙刷',
  ),
  190 => 
  array (
    'cat_id' => '190',
    'cat_name' => '牙膏',
    'measure_unit' => '',
    'parent_id' => '148',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '190',
    'name' => '牙膏',
  ),
  180 => 
  array (
    'cat_id' => '180',
    'cat_name' => '毛巾浴巾',
    'measure_unit' => '',
    'parent_id' => '148',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '180',
    'name' => '毛巾浴巾',
  ),
  147 => 
  array (
    'cat_id' => '147',
    'cat_name' => '家庭清洁',
    'measure_unit' => '',
    'parent_id' => '146',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 1,
    'id' => '147',
    'name' => '家庭清洁',
  ),
  189 => 
  array (
    'cat_id' => '189',
    'cat_name' => '洗衣粉/液/皂',
    'measure_unit' => '',
    'parent_id' => '147',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '189',
    'name' => '洗衣粉/液/皂',
  ),
  150 => 
  array (
    'cat_id' => '150',
    'cat_name' => '纸品湿巾',
    'measure_unit' => '',
    'parent_id' => '146',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 1,
    'id' => '150',
    'name' => '纸品湿巾',
  ),
  186 => 
  array (
    'cat_id' => '186',
    'cat_name' => '卫生巾',
    'measure_unit' => '',
    'parent_id' => '150',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '186',
    'name' => '卫生巾',
  ),
  187 => 
  array (
    'cat_id' => '187',
    'cat_name' => '抽纸',
    'measure_unit' => '',
    'parent_id' => '150',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '187',
    'name' => '抽纸',
  ),
  184 => 
  array (
    'cat_id' => '184',
    'cat_name' => '湿巾',
    'measure_unit' => '',
    'parent_id' => '150',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '184',
    'name' => '湿巾',
  ),
  188 => 
  array (
    'cat_id' => '188',
    'cat_name' => '卷纸',
    'measure_unit' => '',
    'parent_id' => '150',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '188',
    'name' => '卷纸',
  ),
  185 => 
  array (
    'cat_id' => '185',
    'cat_name' => '手帕纸',
    'measure_unit' => '',
    'parent_id' => '150',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '185',
    'name' => '手帕纸',
  ),
  151 => 
  array (
    'cat_id' => '151',
    'cat_name' => '一次性用品',
    'measure_unit' => '',
    'parent_id' => '146',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 1,
    'id' => '151',
    'name' => '一次性用品',
  ),
  179 => 
  array (
    'cat_id' => '179',
    'cat_name' => '棉签',
    'measure_unit' => '',
    'parent_id' => '151',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '179',
    'name' => '棉签',
  ),
  178 => 
  array (
    'cat_id' => '178',
    'cat_name' => '垃圾袋',
    'measure_unit' => '',
    'parent_id' => '151',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '178',
    'name' => '垃圾袋',
  ),
  149 => 
  array (
    'cat_id' => '149',
    'cat_name' => '化妆护肤',
    'measure_unit' => '',
    'parent_id' => '146',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '149',
    'name' => '化妆护肤',
  ),
  152 => 
  array (
    'cat_id' => '152',
    'cat_name' => '化妆品专柜',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '6',
    'goods_num' => 0,
    'level' => 0,
    'id' => '152',
    'name' => '化妆品专柜',
  ),
  155 => 
  array (
    'cat_id' => '155',
    'cat_name' => '面部护理',
    'measure_unit' => '',
    'parent_id' => '152',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '8',
    'goods_num' => 0,
    'level' => 1,
    'id' => '155',
    'name' => '面部护理',
  ),
  224 => 
  array (
    'cat_id' => '224',
    'cat_name' => '精华液/霜/乳',
    'measure_unit' => '',
    'parent_id' => '155',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '224',
    'name' => '精华液/霜/乳',
  ),
  229 => 
  array (
    'cat_id' => '229',
    'cat_name' => '护肤水/乳/霜',
    'measure_unit' => '',
    'parent_id' => '155',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '229',
    'name' => '护肤水/乳/霜',
  ),
  225 => 
  array (
    'cat_id' => '225',
    'cat_name' => '眼霜',
    'measure_unit' => '',
    'parent_id' => '155',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '225',
    'name' => '眼霜',
  ),
  227 => 
  array (
    'cat_id' => '227',
    'cat_name' => '洁面乳/膏',
    'measure_unit' => '',
    'parent_id' => '155',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '227',
    'name' => '洁面乳/膏',
  ),
  228 => 
  array (
    'cat_id' => '228',
    'cat_name' => '面膜',
    'measure_unit' => '',
    'parent_id' => '155',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '228',
    'name' => '面膜',
  ),
  226 => 
  array (
    'cat_id' => '226',
    'cat_name' => '原液',
    'measure_unit' => '',
    'parent_id' => '155',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '226',
    'name' => '原液',
  ),
  230 => 
  array (
    'cat_id' => '230',
    'cat_name' => '去角质',
    'measure_unit' => '',
    'parent_id' => '155',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '7',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '230',
    'name' => '去角质',
  ),
  231 => 
  array (
    'cat_id' => '231',
    'cat_name' => '卸妆水',
    'measure_unit' => '',
    'parent_id' => '155',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '8',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '231',
    'name' => '卸妆水',
  ),
  153 => 
  array (
    'cat_id' => '153',
    'cat_name' => '身体/沐浴',
    'measure_unit' => '',
    'parent_id' => '152',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 1,
    'id' => '153',
    'name' => '身体/沐浴',
  ),
  232 => 
  array (
    'cat_id' => '232',
    'cat_name' => '香皂',
    'measure_unit' => '',
    'parent_id' => '153',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '232',
    'name' => '香皂',
  ),
  233 => 
  array (
    'cat_id' => '233',
    'cat_name' => '洗手液',
    'measure_unit' => '',
    'parent_id' => '153',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '233',
    'name' => '洗手液',
  ),
  234 => 
  array (
    'cat_id' => '234',
    'cat_name' => '沐浴露',
    'measure_unit' => '',
    'parent_id' => '153',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '234',
    'name' => '沐浴露',
  ),
  235 => 
  array (
    'cat_id' => '235',
    'cat_name' => '身体乳',
    'measure_unit' => '',
    'parent_id' => '153',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '235',
    'name' => '身体乳',
  ),
  154 => 
  array (
    'cat_id' => '154',
    'cat_name' => '洗发护发',
    'measure_unit' => '',
    'parent_id' => '152',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 1,
    'id' => '154',
    'name' => '洗发护发',
  ),
  236 => 
  array (
    'cat_id' => '236',
    'cat_name' => '洗发水',
    'measure_unit' => '',
    'parent_id' => '154',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => 3,
    'level' => 2,
    'id' => '236',
    'name' => '洗发水',
  ),
  237 => 
  array (
    'cat_id' => '237',
    'cat_name' => '护发素',
    'measure_unit' => '',
    'parent_id' => '154',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '237',
    'name' => '护发素',
  ),
  156 => 
  array (
    'cat_id' => '156',
    'cat_name' => '口腔护理',
    'measure_unit' => '',
    'parent_id' => '152',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 1,
    'id' => '156',
    'name' => '口腔护理',
  ),
  238 => 
  array (
    'cat_id' => '238',
    'cat_name' => '牙膏',
    'measure_unit' => '',
    'parent_id' => '156',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '238',
    'name' => '牙膏',
  ),
  239 => 
  array (
    'cat_id' => '239',
    'cat_name' => '牙刷',
    'measure_unit' => '',
    'parent_id' => '156',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '239',
    'name' => '牙刷',
  ),
  157 => 
  array (
    'cat_id' => '157',
    'cat_name' => '美容工具',
    'measure_unit' => '',
    'parent_id' => '152',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 1,
    'id' => '157',
    'name' => '美容工具',
  ),
  240 => 
  array (
    'cat_id' => '240',
    'cat_name' => '化妆棉',
    'measure_unit' => '',
    'parent_id' => '157',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '240',
    'name' => '化妆棉',
  ),
  158 => 
  array (
    'cat_id' => '158',
    'cat_name' => '其他',
    'measure_unit' => '',
    'parent_id' => '152',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '158',
    'name' => '其他',
  ),
  159 => 
  array (
    'cat_id' => '159',
    'cat_name' => '内衣配饰馆',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '9',
    'goods_num' => 0,
    'level' => 0,
    'id' => '159',
    'name' => '内衣配饰馆',
  ),
  160 => 
  array (
    'cat_id' => '160',
    'cat_name' => '文胸',
    'measure_unit' => '',
    'parent_id' => '159',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '6',
    'goods_num' => 0,
    'level' => 1,
    'id' => '160',
    'name' => '文胸',
  ),
  169 => 
  array (
    'cat_id' => '169',
    'cat_name' => '少女文胸',
    'measure_unit' => '',
    'parent_id' => '160',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 2,
    'id' => '169',
    'name' => '少女文胸',
  ),
  244 => 
  array (
    'cat_id' => '244',
    'cat_name' => '爱慕秋季新品刺绣女士内衣',
    'measure_unit' => '',
    'parent_id' => '169',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '244',
    'name' => '爱慕秋季新品刺绣女士内衣',
  ),
  170 => 
  array (
    'cat_id' => '170',
    'cat_name' => '哺乳文胸',
    'measure_unit' => '',
    'parent_id' => '160',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '170',
    'name' => '哺乳文胸',
  ),
  174 => 
  array (
    'cat_id' => '174',
    'cat_name' => '无钢圈文胸',
    'measure_unit' => '',
    'parent_id' => '160',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '174',
    'name' => '无钢圈文胸',
  ),
  171 => 
  array (
    'cat_id' => '171',
    'cat_name' => '抹胸式文胸',
    'measure_unit' => '',
    'parent_id' => '160',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '171',
    'name' => '抹胸式文胸',
  ),
  172 => 
  array (
    'cat_id' => '172',
    'cat_name' => '无痕文胸',
    'measure_unit' => '',
    'parent_id' => '160',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 2,
    'id' => '172',
    'name' => '无痕文胸',
  ),
  245 => 
  array (
    'cat_id' => '245',
    'cat_name' => '性感文胸',
    'measure_unit' => '1342',
    'parent_id' => '172',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '245',
    'name' => '性感文胸',
  ),
  173 => 
  array (
    'cat_id' => '173',
    'cat_name' => '背心式文胸',
    'measure_unit' => '',
    'parent_id' => '160',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '173',
    'name' => '背心式文胸',
  ),
  162 => 
  array (
    'cat_id' => '162',
    'cat_name' => '内裤',
    'measure_unit' => '',
    'parent_id' => '159',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '7',
    'goods_num' => 0,
    'level' => 1,
    'id' => '162',
    'name' => '内裤',
  ),
  192 => 
  array (
    'cat_id' => '192',
    'cat_name' => '女士内裤',
    'measure_unit' => '',
    'parent_id' => '162',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '192',
    'name' => '女士内裤',
  ),
  193 => 
  array (
    'cat_id' => '193',
    'cat_name' => '男士内裤',
    'measure_unit' => '',
    'parent_id' => '162',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '193',
    'name' => '男士内裤',
  ),
  194 => 
  array (
    'cat_id' => '194',
    'cat_name' => '孕妇内裤',
    'measure_unit' => '',
    'parent_id' => '162',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '194',
    'name' => '孕妇内裤',
  ),
  195 => 
  array (
    'cat_id' => '195',
    'cat_name' => '儿童内裤',
    'measure_unit' => '',
    'parent_id' => '162',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '195',
    'name' => '儿童内裤',
  ),
  196 => 
  array (
    'cat_id' => '196',
    'cat_name' => '情侣内裤',
    'measure_unit' => '',
    'parent_id' => '162',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '196',
    'name' => '情侣内裤',
  ),
  197 => 
  array (
    'cat_id' => '197',
    'cat_name' => '生理内裤',
    'measure_unit' => '',
    'parent_id' => '162',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '197',
    'name' => '生理内裤',
  ),
  198 => 
  array (
    'cat_id' => '198',
    'cat_name' => '无缝内裤',
    'measure_unit' => '',
    'parent_id' => '162',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '7',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '198',
    'name' => '无缝内裤',
  ),
  163 => 
  array (
    'cat_id' => '163',
    'cat_name' => '家居服',
    'measure_unit' => '',
    'parent_id' => '159',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 1,
    'id' => '163',
    'name' => '家居服',
  ),
  199 => 
  array (
    'cat_id' => '199',
    'cat_name' => '家居裤',
    'measure_unit' => '',
    'parent_id' => '163',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '199',
    'name' => '家居裤',
  ),
  200 => 
  array (
    'cat_id' => '200',
    'cat_name' => '睡裙',
    'measure_unit' => '',
    'parent_id' => '163',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '200',
    'name' => '睡裙',
  ),
  201 => 
  array (
    'cat_id' => '201',
    'cat_name' => '睡袍',
    'measure_unit' => '',
    'parent_id' => '163',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '201',
    'name' => '睡袍',
  ),
  202 => 
  array (
    'cat_id' => '202',
    'cat_name' => '瑜伽服',
    'measure_unit' => '',
    'parent_id' => '163',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '202',
    'name' => '瑜伽服',
  ),
  164 => 
  array (
    'cat_id' => '164',
    'cat_name' => '孕妇系列',
    'measure_unit' => '',
    'parent_id' => '159',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 1,
    'id' => '164',
    'name' => '孕妇系列',
  ),
  203 => 
  array (
    'cat_id' => '203',
    'cat_name' => '孕妇衣',
    'measure_unit' => '',
    'parent_id' => '164',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '203',
    'name' => '孕妇衣',
  ),
  204 => 
  array (
    'cat_id' => '204',
    'cat_name' => '孕妇打底裤',
    'measure_unit' => '',
    'parent_id' => '164',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '204',
    'name' => '孕妇打底裤',
  ),
  205 => 
  array (
    'cat_id' => '205',
    'cat_name' => '孕妇内裤',
    'measure_unit' => '',
    'parent_id' => '164',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '205',
    'name' => '孕妇内裤',
  ),
  206 => 
  array (
    'cat_id' => '206',
    'cat_name' => '哺乳文胸',
    'measure_unit' => '',
    'parent_id' => '164',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '206',
    'name' => '哺乳文胸',
  ),
  165 => 
  array (
    'cat_id' => '165',
    'cat_name' => '打底衫',
    'measure_unit' => '',
    'parent_id' => '159',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 1,
    'id' => '165',
    'name' => '打底衫',
  ),
  207 => 
  array (
    'cat_id' => '207',
    'cat_name' => '披肩',
    'measure_unit' => '',
    'parent_id' => '165',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '207',
    'name' => '披肩',
  ),
  208 => 
  array (
    'cat_id' => '208',
    'cat_name' => '吊带背心',
    'measure_unit' => '',
    'parent_id' => '165',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '208',
    'name' => '吊带背心',
  ),
  209 => 
  array (
    'cat_id' => '209',
    'cat_name' => 'T恤',
    'measure_unit' => '',
    'parent_id' => '165',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '209',
    'name' => 'T恤',
  ),
  210 => 
  array (
    'cat_id' => '210',
    'cat_name' => '裹胸',
    'measure_unit' => '',
    'parent_id' => '165',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '210',
    'name' => '裹胸',
  ),
  211 => 
  array (
    'cat_id' => '211',
    'cat_name' => '防晒衣',
    'measure_unit' => '',
    'parent_id' => '165',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '211',
    'name' => '防晒衣',
  ),
  166 => 
  array (
    'cat_id' => '166',
    'cat_name' => '秋衣秋裤',
    'measure_unit' => '',
    'parent_id' => '159',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 1,
    'id' => '166',
    'name' => '秋衣秋裤',
  ),
  212 => 
  array (
    'cat_id' => '212',
    'cat_name' => '女款',
    'measure_unit' => '',
    'parent_id' => '166',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '212',
    'name' => '女款',
  ),
  213 => 
  array (
    'cat_id' => '213',
    'cat_name' => '男款',
    'measure_unit' => '',
    'parent_id' => '166',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '213',
    'name' => '男款',
  ),
  167 => 
  array (
    'cat_id' => '167',
    'cat_name' => '保暖系列',
    'measure_unit' => '',
    'parent_id' => '159',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '7',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 1,
    'id' => '167',
    'name' => '保暖系列',
  ),
  215 => 
  array (
    'cat_id' => '215',
    'cat_name' => '女款',
    'measure_unit' => '',
    'parent_id' => '167',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '215',
    'name' => '女款',
  ),
  214 => 
  array (
    'cat_id' => '214',
    'cat_name' => '男款',
    'measure_unit' => '',
    'parent_id' => '167',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '214',
    'name' => '男款',
  ),
  168 => 
  array (
    'cat_id' => '168',
    'cat_name' => '袜子系列',
    'measure_unit' => '',
    'parent_id' => '159',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '8',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 1,
    'id' => '168',
    'name' => '袜子系列',
  ),
  216 => 
  array (
    'cat_id' => '216',
    'cat_name' => '短袜',
    'measure_unit' => '',
    'parent_id' => '168',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '216',
    'name' => '短袜',
  ),
  217 => 
  array (
    'cat_id' => '217',
    'cat_name' => '连体袜',
    'measure_unit' => '',
    'parent_id' => '168',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '217',
    'name' => '连体袜',
  ),
  218 => 
  array (
    'cat_id' => '218',
    'cat_name' => '儿童袜',
    'measure_unit' => '',
    'parent_id' => '168',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '218',
    'name' => '儿童袜',
  ),
  219 => 
  array (
    'cat_id' => '219',
    'cat_name' => '配饰系列',
    'measure_unit' => '',
    'parent_id' => '159',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '9',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 1,
    'id' => '219',
    'name' => '配饰系列',
  ),
  220 => 
  array (
    'cat_id' => '220',
    'cat_name' => '肩带',
    'measure_unit' => '',
    'parent_id' => '219',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '220',
    'name' => '肩带',
  ),
  221 => 
  array (
    'cat_id' => '221',
    'cat_name' => '排扣',
    'measure_unit' => '',
    'parent_id' => '219',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '221',
    'name' => '排扣',
  ),
  222 => 
  array (
    'cat_id' => '222',
    'cat_name' => '插垫',
    'measure_unit' => '',
    'parent_id' => '219',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '222',
    'name' => '插垫',
  ),
  223 => 
  array (
    'cat_id' => '223',
    'cat_name' => '胸贴',
    'measure_unit' => '',
    'parent_id' => '219',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '223',
    'name' => '胸贴',
  ),
  175 => 
  array (
    'cat_id' => '175',
    'cat_name' => '童装店',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '175',
    'name' => '童装店',
  ),
  177 => 
  array (
    'cat_id' => '177',
    'cat_name' => '文具店',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '177',
    'name' => '文具店',
  ),
  176 => 
  array (
    'cat_id' => '176',
    'cat_name' => '鞋店',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '176',
    'name' => '鞋店',
  ),
  1 => 
  array (
    'cat_id' => '1',
    'cat_name' => '彩妆',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 0,
    'id' => '1',
    'name' => '彩妆',
  ),
  4 => 
  array (
    'cat_id' => '4',
    'cat_name' => '眼部彩妆',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '0',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 1,
    'id' => '4',
    'name' => '眼部彩妆',
  ),
  50 => 
  array (
    'cat_id' => '50',
    'cat_name' => '眉粉眉笔',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '50',
    'name' => '眉粉眉笔',
  ),
  47 => 
  array (
    'cat_id' => '47',
    'cat_name' => '眼线',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '47',
    'name' => '眼线',
  ),
  48 => 
  array (
    'cat_id' => '48',
    'cat_name' => '眼影',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '48',
    'name' => '眼影',
  ),
  49 => 
  array (
    'cat_id' => '49',
    'cat_name' => '睫毛',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '49',
    'name' => '睫毛',
  ),
  5 => 
  array (
    'cat_id' => '5',
    'cat_name' => '面部彩妆',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '1',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 1,
    'id' => '5',
    'name' => '面部彩妆',
  ),
  53 => 
  array (
    'cat_id' => '53',
    'cat_name' => '粉饼',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '53',
    'name' => '粉饼',
  ),
  54 => 
  array (
    'cat_id' => '54',
    'cat_name' => '散粉',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '54',
    'name' => '散粉',
  ),
  51 => 
  array (
    'cat_id' => '51',
    'cat_name' => 'BB霜',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '51',
    'name' => 'BB霜',
  ),
  55 => 
  array (
    'cat_id' => '55',
    'cat_name' => '隔离霜',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '55',
    'name' => '隔离霜',
  ),
  52 => 
  array (
    'cat_id' => '52',
    'cat_name' => '粉底',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '52',
    'name' => '粉底',
  ),
  3 => 
  array (
    'cat_id' => '3',
    'cat_name' => '彩妆套装',
    'measure_unit' => '台',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '2',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 1,
    'id' => '3',
    'name' => '彩妆套装',
  ),
  59 => 
  array (
    'cat_id' => '59',
    'cat_name' => '卸妆',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '59',
    'name' => '卸妆',
  ),
  56 => 
  array (
    'cat_id' => '56',
    'cat_name' => '眼影',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '56',
    'name' => '眼影',
  ),
  60 => 
  array (
    'cat_id' => '60',
    'cat_name' => '浓密卷翘',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '60',
    'name' => '浓密卷翘',
  ),
  57 => 
  array (
    'cat_id' => '57',
    'cat_name' => '修容',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '57',
    'name' => '修容',
  ),
  58 => 
  array (
    'cat_id' => '58',
    'cat_name' => '润唇',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '58',
    'name' => '润唇',
  ),
  2 => 
  array (
    'cat_id' => '2',
    'cat_name' => '其他彩妆',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => 0,
    'level' => 1,
    'id' => '2',
    'name' => '其他彩妆',
  ),
  62 => 
  array (
    'cat_id' => '62',
    'cat_name' => '唇妆',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '62',
    'name' => '唇妆',
  ),
  66 => 
  array (
    'cat_id' => '66',
    'cat_name' => '底妆定妆',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '66',
    'name' => '底妆定妆',
  ),
  63 => 
  array (
    'cat_id' => '63',
    'cat_name' => '美甲',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '63',
    'name' => '美甲',
  ),
  64 => 
  array (
    'cat_id' => '64',
    'cat_name' => '修容',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '64',
    'name' => '修容',
  ),
  61 => 
  array (
    'cat_id' => '61',
    'cat_name' => '腮红',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '61',
    'name' => '腮红',
  ),
  65 => 
  array (
    'cat_id' => '65',
    'cat_name' => '遮瑕',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '65',
    'name' => '遮瑕',
  ),
  18 => 
  array (
    'cat_id' => '18',
    'cat_name' => '美容工具',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 0,
    'id' => '18',
    'name' => '美容工具',
  ),
  130 => 
  array (
    'cat_id' => '130',
    'cat_name' => '美体工具',
    'measure_unit' => '',
    'parent_id' => '18',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '70',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 1,
    'id' => '130',
    'name' => '美体工具',
  ),
  134 => 
  array (
    'cat_id' => '134',
    'cat_name' => '美甲工具',
    'measure_unit' => '',
    'parent_id' => '130',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '134',
    'name' => '美甲工具',
  ),
  135 => 
  array (
    'cat_id' => '135',
    'cat_name' => '瘦身纤体',
    'measure_unit' => '',
    'parent_id' => '130',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '135',
    'name' => '瘦身纤体',
  ),
  131 => 
  array (
    'cat_id' => '131',
    'cat_name' => '化妆工具',
    'measure_unit' => '',
    'parent_id' => '18',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '71',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 1,
    'id' => '131',
    'name' => '化妆工具',
  ),
  137 => 
  array (
    'cat_id' => '137',
    'cat_name' => '辅助化妆',
    'measure_unit' => '',
    'parent_id' => '131',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '137',
    'name' => '辅助化妆',
  ),
  138 => 
  array (
    'cat_id' => '138',
    'cat_name' => '定妆',
    'measure_unit' => '',
    'parent_id' => '131',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '138',
    'name' => '定妆',
  ),
  139 => 
  array (
    'cat_id' => '139',
    'cat_name' => '艾黛儿',
    'measure_unit' => '',
    'parent_id' => '131',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '139',
    'name' => '艾黛儿',
  ),
  136 => 
  array (
    'cat_id' => '136',
    'cat_name' => '化妆镜',
    'measure_unit' => '',
    'parent_id' => '131',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '136',
    'name' => '化妆镜',
  ),
  132 => 
  array (
    'cat_id' => '132',
    'cat_name' => '美发工具',
    'measure_unit' => '',
    'parent_id' => '18',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '72',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 1,
    'id' => '132',
    'name' => '美发工具',
  ),
  140 => 
  array (
    'cat_id' => '140',
    'cat_name' => '护发养发',
    'measure_unit' => '',
    'parent_id' => '132',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '140',
    'name' => '护发养发',
  ),
  141 => 
  array (
    'cat_id' => '141',
    'cat_name' => '发型定型',
    'measure_unit' => '',
    'parent_id' => '132',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '141',
    'name' => '发型定型',
  ),
  133 => 
  array (
    'cat_id' => '133',
    'cat_name' => '日用收纳',
    'measure_unit' => '',
    'parent_id' => '18',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '73',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 1,
    'id' => '133',
    'name' => '日用收纳',
  ),
  143 => 
  array (
    'cat_id' => '143',
    'cat_name' => '化妆包',
    'measure_unit' => '',
    'parent_id' => '133',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '143',
    'name' => '化妆包',
  ),
  144 => 
  array (
    'cat_id' => '144',
    'cat_name' => '雅诗兰黛',
    'measure_unit' => '',
    'parent_id' => '133',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '144',
    'name' => '雅诗兰黛',
  ),
  142 => 
  array (
    'cat_id' => '142',
    'cat_name' => '收纳',
    'measure_unit' => '',
    'parent_id' => '133',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '142',
    'name' => '收纳',
  ),
  12 => 
  array (
    'cat_id' => '12',
    'cat_name' => '男士',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 0,
    'id' => '12',
    'name' => '男士',
  ),
  14 => 
  array (
    'cat_id' => '14',
    'cat_name' => '面部护理',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '7',
    'goods_num' => 0,
    'level' => 1,
    'id' => '14',
    'name' => '面部护理',
  ),
  72 => 
  array (
    'cat_id' => '72',
    'cat_name' => '面霜',
    'measure_unit' => '',
    'parent_id' => '14',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '72',
    'name' => '面霜',
  ),
  69 => 
  array (
    'cat_id' => '69',
    'cat_name' => '乳液',
    'measure_unit' => '',
    'parent_id' => '14',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '69',
    'name' => '乳液',
  ),
  73 => 
  array (
    'cat_id' => '73',
    'cat_name' => '面膜',
    'measure_unit' => '',
    'parent_id' => '14',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '73',
    'name' => '面膜',
  ),
  70 => 
  array (
    'cat_id' => '70',
    'cat_name' => '眼霜',
    'measure_unit' => '',
    'parent_id' => '14',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '70',
    'name' => '眼霜',
  ),
  67 => 
  array (
    'cat_id' => '67',
    'cat_name' => '洁面',
    'measure_unit' => '',
    'parent_id' => '14',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '67',
    'name' => '洁面',
  ),
  71 => 
  array (
    'cat_id' => '71',
    'cat_name' => '精华',
    'measure_unit' => '',
    'parent_id' => '14',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '71',
    'name' => '精华',
  ),
  68 => 
  array (
    'cat_id' => '68',
    'cat_name' => '爽肤',
    'measure_unit' => '',
    'parent_id' => '14',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '68',
    'name' => '爽肤',
  ),
  15 => 
  array (
    'cat_id' => '15',
    'cat_name' => '身体护理',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 1,
    'id' => '15',
    'name' => '身体护理',
  ),
  75 => 
  array (
    'cat_id' => '75',
    'cat_name' => '清洁',
    'measure_unit' => '',
    'parent_id' => '15',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '75',
    'name' => '清洁',
  ),
  76 => 
  array (
    'cat_id' => '76',
    'cat_name' => '香体喷雾',
    'measure_unit' => '',
    'parent_id' => '15',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '76',
    'name' => '香体喷雾',
  ),
  77 => 
  array (
    'cat_id' => '77',
    'cat_name' => '阿迪达斯',
    'measure_unit' => '',
    'parent_id' => '15',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '77',
    'name' => '阿迪达斯',
  ),
  74 => 
  array (
    'cat_id' => '74',
    'cat_name' => '沐浴',
    'measure_unit' => '',
    'parent_id' => '15',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '74',
    'name' => '沐浴',
  ),
  13 => 
  array (
    'cat_id' => '13',
    'cat_name' => '其他护理',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 1,
    'id' => '13',
    'name' => '其他护理',
  ),
  78 => 
  array (
    'cat_id' => '78',
    'cat_name' => '防晒',
    'measure_unit' => '',
    'parent_id' => '13',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '78',
    'name' => '防晒',
  ),
  79 => 
  array (
    'cat_id' => '79',
    'cat_name' => '剃须',
    'measure_unit' => '',
    'parent_id' => '13',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '79',
    'name' => '剃须',
  ),
  80 => 
  array (
    'cat_id' => '80',
    'cat_name' => 'BB霜',
    'measure_unit' => '',
    'parent_id' => '13',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '80',
    'name' => 'BB霜',
  ),
  46 => 
  array (
    'cat_id' => '46',
    'cat_name' => '男士套装',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 1,
    'id' => '46',
    'name' => '男士套装',
  ),
  85 => 
  array (
    'cat_id' => '85',
    'cat_name' => '碧欧泉',
    'measure_unit' => '',
    'parent_id' => '46',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '85',
    'name' => '碧欧泉',
  ),
  82 => 
  array (
    'cat_id' => '82',
    'cat_name' => '活肤',
    'measure_unit' => '',
    'parent_id' => '46',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '82',
    'name' => '活肤',
  ),
  83 => 
  array (
    'cat_id' => '83',
    'cat_name' => '兰芝',
    'measure_unit' => '',
    'parent_id' => '46',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '83',
    'name' => '兰芝',
  ),
  84 => 
  array (
    'cat_id' => '84',
    'cat_name' => '欧莱雅',
    'measure_unit' => '',
    'parent_id' => '46',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '84',
    'name' => '欧莱雅',
  ),
  81 => 
  array (
    'cat_id' => '81',
    'cat_name' => '保湿',
    'measure_unit' => '',
    'parent_id' => '46',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '81',
    'name' => '保湿',
  ),
  16 => 
  array (
    'cat_id' => '16',
    'cat_name' => '香氛',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 0,
    'id' => '16',
    'name' => '香氛',
  ),
  86 => 
  array (
    'cat_id' => '86',
    'cat_name' => '女士香水',
    'measure_unit' => '',
    'parent_id' => '16',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 1,
    'id' => '86',
    'name' => '女士香水',
  ),
  94 => 
  array (
    'cat_id' => '94',
    'cat_name' => '菲拉格慕',
    'measure_unit' => '',
    'parent_id' => '86',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '94',
    'name' => '菲拉格慕',
  ),
  91 => 
  array (
    'cat_id' => '91',
    'cat_name' => '花香调',
    'measure_unit' => '',
    'parent_id' => '86',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '91',
    'name' => '花香调',
  ),
  92 => 
  array (
    'cat_id' => '92',
    'cat_name' => '迪奥',
    'measure_unit' => '',
    'parent_id' => '86',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '92',
    'name' => '迪奥',
  ),
  93 => 
  array (
    'cat_id' => '93',
    'cat_name' => '安娜苏',
    'measure_unit' => '',
    'parent_id' => '86',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '93',
    'name' => '安娜苏',
  ),
  90 => 
  array (
    'cat_id' => '90',
    'cat_name' => '淡香',
    'measure_unit' => '',
    'parent_id' => '86',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '90',
    'name' => '淡香',
  ),
  87 => 
  array (
    'cat_id' => '87',
    'cat_name' => '男士香水',
    'measure_unit' => '',
    'parent_id' => '16',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '51',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 1,
    'id' => '87',
    'name' => '男士香水',
  ),
  98 => 
  array (
    'cat_id' => '98',
    'cat_name' => '宝格丽',
    'measure_unit' => '',
    'parent_id' => '87',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '98',
    'name' => '宝格丽',
  ),
  95 => 
  array (
    'cat_id' => '95',
    'cat_name' => '淡香',
    'measure_unit' => '',
    'parent_id' => '87',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '95',
    'name' => '淡香',
  ),
  99 => 
  array (
    'cat_id' => '99',
    'cat_name' => '阿迪达斯',
    'measure_unit' => '',
    'parent_id' => '87',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '99',
    'name' => '阿迪达斯',
  ),
  96 => 
  array (
    'cat_id' => '96',
    'cat_name' => '海洋香调',
    'measure_unit' => '',
    'parent_id' => '87',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '96',
    'name' => '海洋香调',
  ),
  97 => 
  array (
    'cat_id' => '97',
    'cat_name' => '博柏利',
    'measure_unit' => '',
    'parent_id' => '87',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '97',
    'name' => '博柏利',
  ),
  88 => 
  array (
    'cat_id' => '88',
    'cat_name' => '中性香水',
    'measure_unit' => '',
    'parent_id' => '16',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '52',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 1,
    'id' => '88',
    'name' => '中性香水',
  ),
  101 => 
  array (
    'cat_id' => '101',
    'cat_name' => '花果香调',
    'measure_unit' => '',
    'parent_id' => '88',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '101',
    'name' => '花果香调',
  ),
  102 => 
  array (
    'cat_id' => '102',
    'cat_name' => '爱马仕',
    'measure_unit' => '',
    'parent_id' => '88',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '102',
    'name' => '爱马仕',
  ),
  103 => 
  array (
    'cat_id' => '103',
    'cat_name' => '凯文克莱',
    'measure_unit' => '',
    'parent_id' => '88',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '103',
    'name' => '凯文克莱',
  ),
  100 => 
  array (
    'cat_id' => '100',
    'cat_name' => '淡香',
    'measure_unit' => '',
    'parent_id' => '88',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '100',
    'name' => '淡香',
  ),
  89 => 
  array (
    'cat_id' => '89',
    'cat_name' => '香水套装',
    'measure_unit' => '',
    'parent_id' => '16',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '53',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 1,
    'id' => '89',
    'name' => '香水套装',
  ),
  107 => 
  array (
    'cat_id' => '107',
    'cat_name' => '花果香调',
    'measure_unit' => '',
    'parent_id' => '89',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '107',
    'name' => '花果香调',
  ),
  104 => 
  array (
    'cat_id' => '104',
    'cat_name' => '淡香',
    'measure_unit' => '',
    'parent_id' => '89',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '104',
    'name' => '淡香',
  ),
  108 => 
  array (
    'cat_id' => '108',
    'cat_name' => '草木香调',
    'measure_unit' => '',
    'parent_id' => '89',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '108',
    'name' => '草木香调',
  ),
  105 => 
  array (
    'cat_id' => '105',
    'cat_name' => '香体',
    'measure_unit' => '',
    'parent_id' => '89',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '105',
    'name' => '香体',
  ),
  106 => 
  array (
    'cat_id' => '106',
    'cat_name' => '花香调',
    'measure_unit' => '',
    'parent_id' => '89',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '106',
    'name' => '花香调',
  ),
  6 => 
  array (
    'cat_id' => '6',
    'cat_name' => '护肤',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 0,
    'id' => '6',
    'name' => '护肤',
  ),
  11 => 
  array (
    'cat_id' => '11',
    'cat_name' => '护肤套装',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 1,
    'id' => '11',
    'name' => '护肤套装',
  ),
  43 => 
  array (
    'cat_id' => '43',
    'cat_name' => '嫩肤',
    'measure_unit' => '',
    'parent_id' => '11',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '43',
    'name' => '嫩肤',
  ),
  44 => 
  array (
    'cat_id' => '44',
    'cat_name' => '补水',
    'measure_unit' => '',
    'parent_id' => '11',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '44',
    'name' => '补水',
  ),
  41 => 
  array (
    'cat_id' => '41',
    'cat_name' => '美白',
    'measure_unit' => '',
    'parent_id' => '11',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '41',
    'name' => '美白',
  ),
  45 => 
  array (
    'cat_id' => '45',
    'cat_name' => '紧致去皱',
    'measure_unit' => '',
    'parent_id' => '11',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '45',
    'name' => '紧致去皱',
  ),
  42 => 
  array (
    'cat_id' => '42',
    'cat_name' => '保湿',
    'measure_unit' => '',
    'parent_id' => '11',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '42',
    'name' => '保湿',
  ),
  7 => 
  array (
    'cat_id' => '7',
    'cat_name' => '面部护理',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '9',
    'goods_num' => 0,
    'level' => 1,
    'id' => '7',
    'name' => '面部护理',
  ),
  27 => 
  array (
    'cat_id' => '27',
    'cat_name' => '面油',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '27',
    'name' => '面油',
  ),
  24 => 
  array (
    'cat_id' => '24',
    'cat_name' => '化妆水',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '24',
    'name' => '化妆水',
  ),
  21 => 
  array (
    'cat_id' => '21',
    'cat_name' => '卸妆',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '21',
    'name' => '卸妆',
  ),
  25 => 
  array (
    'cat_id' => '25',
    'cat_name' => '乳液',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '25',
    'name' => '乳液',
  ),
  22 => 
  array (
    'cat_id' => '22',
    'cat_name' => '防晒',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '22',
    'name' => '防晒',
  ),
  19 => 
  array (
    'cat_id' => '19',
    'cat_name' => '洁面',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '19',
    'name' => '洁面',
  ),
  26 => 
  array (
    'cat_id' => '26',
    'cat_name' => '面霜',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '26',
    'name' => '面霜',
  ),
  23 => 
  array (
    'cat_id' => '23',
    'cat_name' => '精华',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '23',
    'name' => '精华',
  ),
  20 => 
  array (
    'cat_id' => '20',
    'cat_name' => '面膜',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '20',
    'name' => '面膜',
  ),
  8 => 
  array (
    'cat_id' => '8',
    'cat_name' => '眼部护理',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 1,
    'id' => '8',
    'name' => '眼部护理',
  ),
  30 => 
  array (
    'cat_id' => '30',
    'cat_name' => '去眼纹',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '30',
    'name' => '去眼纹',
  ),
  31 => 
  array (
    'cat_id' => '31',
    'cat_name' => '去眼袋',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '31',
    'name' => '去眼袋',
  ),
  28 => 
  array (
    'cat_id' => '28',
    'cat_name' => '保湿',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '28',
    'name' => '保湿',
  ),
  32 => 
  array (
    'cat_id' => '32',
    'cat_name' => '去黑眼圈',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '32',
    'name' => '去黑眼圈',
  ),
  29 => 
  array (
    'cat_id' => '29',
    'cat_name' => '去浮肿',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '29',
    'name' => '去浮肿',
  ),
  9 => 
  array (
    'cat_id' => '9',
    'cat_name' => '其他护理',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '8',
    'goods_num' => 0,
    'level' => 1,
    'id' => '9',
    'name' => '其他护理',
  ),
  40 => 
  array (
    'cat_id' => '40',
    'cat_name' => '保健食品',
    'measure_unit' => '',
    'parent_id' => '9',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '40',
    'name' => '保健食品',
  ),
  37 => 
  array (
    'cat_id' => '37',
    'cat_name' => '祛痘祛斑',
    'measure_unit' => '',
    'parent_id' => '9',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '37',
    'name' => '祛痘祛斑',
  ),
  34 => 
  array (
    'cat_id' => '34',
    'cat_name' => '喷雾',
    'measure_unit' => '',
    'parent_id' => '9',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '34',
    'name' => '喷雾',
  ),
  38 => 
  array (
    'cat_id' => '38',
    'cat_name' => 'T区护理',
    'measure_unit' => '',
    'parent_id' => '9',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '38',
    'name' => 'T区护理',
  ),
  35 => 
  array (
    'cat_id' => '35',
    'cat_name' => '啫喱',
    'measure_unit' => '',
    'parent_id' => '9',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '35',
    'name' => '啫喱',
  ),
  39 => 
  array (
    'cat_id' => '39',
    'cat_name' => '颈霜',
    'measure_unit' => '',
    'parent_id' => '9',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '39',
    'name' => '颈霜',
  ),
  36 => 
  array (
    'cat_id' => '36',
    'cat_name' => '角质按摩',
    'measure_unit' => '',
    'parent_id' => '9',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '36',
    'name' => '角质按摩',
  ),
  33 => 
  array (
    'cat_id' => '33',
    'cat_name' => '护唇',
    'measure_unit' => '',
    'parent_id' => '9',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '33',
    'name' => '护唇',
  ),
  243 => 
  array (
    'cat_id' => '243',
    'cat_name' => '文胸',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '243',
    'name' => '文胸',
  ),
  17 => 
  array (
    'cat_id' => '17',
    'cat_name' => '身体护理',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 0,
    'id' => '17',
    'name' => '身体护理',
  ),
  109 => 
  array (
    'cat_id' => '109',
    'cat_name' => '身体护理',
    'measure_unit' => '',
    'parent_id' => '17',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '60',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 1,
    'id' => '109',
    'name' => '身体护理',
  ),
  114 => 
  array (
    'cat_id' => '114',
    'cat_name' => '脱毛',
    'measure_unit' => '',
    'parent_id' => '109',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '114',
    'name' => '脱毛',
  ),
  115 => 
  array (
    'cat_id' => '115',
    'cat_name' => '手足护理',
    'measure_unit' => '',
    'parent_id' => '109',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '115',
    'name' => '手足护理',
  ),
  116 => 
  array (
    'cat_id' => '116',
    'cat_name' => '香体止汗',
    'measure_unit' => '',
    'parent_id' => '109',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '116',
    'name' => '香体止汗',
  ),
  113 => 
  array (
    'cat_id' => '113',
    'cat_name' => '沐浴',
    'measure_unit' => '',
    'parent_id' => '109',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '113',
    'name' => '沐浴',
  ),
  117 => 
  array (
    'cat_id' => '117',
    'cat_name' => '其他护理',
    'measure_unit' => '',
    'parent_id' => '109',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '117',
    'name' => '其他护理',
  ),
  110 => 
  array (
    'cat_id' => '110',
    'cat_name' => '丰胸瘦身',
    'measure_unit' => '',
    'parent_id' => '17',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '61',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 1,
    'id' => '110',
    'name' => '丰胸瘦身',
  ),
  118 => 
  array (
    'cat_id' => '118',
    'cat_name' => '丰胸塑臀',
    'measure_unit' => '',
    'parent_id' => '110',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '118',
    'name' => '丰胸塑臀',
  ),
  119 => 
  array (
    'cat_id' => '119',
    'cat_name' => '纤体瘦身',
    'measure_unit' => '',
    'parent_id' => '110',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '119',
    'name' => '纤体瘦身',
  ),
  120 => 
  array (
    'cat_id' => '120',
    'cat_name' => '精油护理',
    'measure_unit' => '',
    'parent_id' => '110',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '120',
    'name' => '精油护理',
  ),
  111 => 
  array (
    'cat_id' => '111',
    'cat_name' => '美发护发',
    'measure_unit' => '',
    'parent_id' => '17',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '62',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 1,
    'id' => '111',
    'name' => '美发护发',
  ),
  124 => 
  array (
    'cat_id' => '124',
    'cat_name' => '焗油',
    'measure_unit' => '',
    'parent_id' => '111',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '124',
    'name' => '焗油',
  ),
  121 => 
  array (
    'cat_id' => '121',
    'cat_name' => '洗发',
    'measure_unit' => '',
    'parent_id' => '111',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '121',
    'name' => '洗发',
  ),
  125 => 
  array (
    'cat_id' => '125',
    'cat_name' => '美发造型',
    'measure_unit' => '',
    'parent_id' => '111',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '125',
    'name' => '美发造型',
  ),
  122 => 
  array (
    'cat_id' => '122',
    'cat_name' => '护发',
    'measure_unit' => '',
    'parent_id' => '111',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '122',
    'name' => '护发',
  ),
  123 => 
  array (
    'cat_id' => '123',
    'cat_name' => '染发',
    'measure_unit' => '',
    'parent_id' => '111',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '123',
    'name' => '染发',
  ),
  112 => 
  array (
    'cat_id' => '112',
    'cat_name' => '洗护套装',
    'measure_unit' => '',
    'parent_id' => '17',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '63',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 1,
    'id' => '112',
    'name' => '洗护套装',
  ),
  127 => 
  array (
    'cat_id' => '127',
    'cat_name' => '沐浴',
    'measure_unit' => '',
    'parent_id' => '112',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '127',
    'name' => '沐浴',
  ),
  128 => 
  array (
    'cat_id' => '128',
    'cat_name' => '护发养发',
    'measure_unit' => '',
    'parent_id' => '112',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '128',
    'name' => '护发养发',
  ),
  129 => 
  array (
    'cat_id' => '129',
    'cat_name' => '美体套装',
    'measure_unit' => '',
    'parent_id' => '112',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '129',
    'name' => '美体套装',
  ),
  126 => 
  array (
    'cat_id' => '126',
    'cat_name' => '保湿',
    'measure_unit' => '',
    'parent_id' => '112',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '126',
    'name' => '保湿',
  ),
);
?>